apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: example
    app.kubernetes.io/version: 0.0.0-devel
  name: example
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: example
  type: ClusterIP
